# Generated by Django 5.1.4 on 2024-12-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_rename_types_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='gfg_name',
            new_name='quiz_category',
        ),
    ]
